### ISSUE TITLE
Allow optional variables?

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#197] opened 2016-09-07 06:14 UTC
If I declare a variable type to be nullable (e.g. `query people(cursor: Int) { .. }` as opposed to `Int!`), I don't think we should throw an invariant error if the `cursor` variable is missing.

**Comment by jbaxleyiii** [comment] 2016-09-07 13:08
@tmeasday this is a great point! I'll get that fixed and out!

**Comment by jbaxleyiii** [comment] 2016-09-07 13:22
@tmeasday I don't think AC allows this?

```js
Error: The inline argument "first" is expected as a variable but was not provided.
      at valueToObjectRepresentation (/Users/james.baxley/Products/apollo/react-apollo/node_modules/apollo-client/data/storeUtils.js:34:19)
```

**Comment by jbaxleyiii** [comment] 2016-09-07 13:27
We could pass `null` as the value though if they are missing.

**Comment by jbaxleyiii** [comment] 2016-09-07 13:57
fixed in #200 (going out today!)

**Closed by jbaxleyiii** 2016-09-07 13:57 UTC
Labels: @next, in progress

**Comment by jbaxleyiii** [comment] 2016-09-07 13:58
should be out soon! https://github.com/apollostack/react-apollo/releases/tag/v0.5.2

**Comment by tmeasday** [comment] 2016-09-08 00:09
Do you think we should fix this in AC? Maybe AC can be more strict and force you to explicit about your null

**Comment by jbaxleyiii** [comment] 2016-09-08 01:21
@tmeasday there is an issue open in AC about it where @stubailo was on the fence. I'm happy to do that or keep this shim 🎉

**Comment by imthehell** [comment] 2016-11-26 21:51
@jbaxleyiii the fixing is not working for me. I have react-apollo v0.6 but it is returning me the same error also if the variable is optional

`Error: The inline argument "first" is expected as a variable but was not provided.`

**Comment by tmeasday** [comment] 2016-11-27 21:23
@imthehell perhaps we can open a new issue about this with a reproduction? #200 included a test for this so there must a subtlety in your use case that the test isn't covering.

**Comment by imthehell** [comment] 2016-11-27 22:25
Mi query is the following 
`query aaaList($page: String, $size: Int, $kind: String, $AFilters: AFilterType, $BFilters: BFilterType) {`

so last two vars are custom types. If one of those custom type vars is missing, the error is returned. Could be that it is not working with custom types but only with "String, Int, etc.)?

**Comment by tmeasday** [comment] 2016-11-27 23:51
@imthehell it seems unlikely to me. I don't think RA or AC would even know that it's looking at custom types. But it's possible. Have you tried running the test from #200?

**Comment by samuelhorwitz** [comment] 2016-11-28 06:40
I'm seeing this issue as well. Maybe it's too late and I'm misreading completely but the test case in #200 does not seem to actually work as intended. Both tests (for failing when variable is required and not failing when variable isn't required) pass variables to the query. This means there does not seem to ever actually be a test in which *no* variable is passed to the query which means a regression could have occurred.

**Comment by tmeasday** [comment] 2016-11-28 21:12
@samuelhorwitz `react-apollo` will always pass *some* variables into the query: https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx so I don't know if that's relevant.

**Comment by beornborn** [comment] 2016-11-29 16:32
@tmeasday @jbaxleyiii 
have the same issue.
mutation: 

```
export const sendNomination = gql`
  mutation emailInvitation($id: Int!, $to: String!, $cc: String, $subject: String, $body: String) {
    emailInvitation(id: $id, to: $to, cc: $cc, subject: $subject, body: $body) {
      status
      errors
    }
  }
`
```

error: 
http://prntscr.com/dd9kep

react-apollo@0.6.0

**Comment by glasser** [comment] 2016-11-30 19:55
@beornborn Can you share a broader reproduction? The fix in #200 is specifically to using the `graphql` higher-order component with react-apollo; maybe your mutation isn't going through that? Note that the error you're seeing comes from apollo-client, not react-apollo.

**Comment by glasser** [comment] 2016-11-30 21:39
OK, I think the issue is in https://github.com/apollostack/react-apollo/blob/8c1f02fb610ff8ee9287120f4de6b8e75f25d6ff/src/graphql.tsx#L161

```
      if (opts.variables || !operation.variables.length) return opts;
```

ie, if you specify *any* variables in your mapPropsToOptions function, then it completely skips the "send nulls for unmentioned things" thing.  This seems wrong, no?

**Comment by glasser** [comment] 2016-11-30 21:46
See also https://github.com/apollostack/apollo-client/issues/561

**Comment by beornborn** [comment] 2016-12-01 02:44
@glasser yes, I used apolloClient directly, sorry for the irrelevant message

**Comment by tmeasday** [comment] 2016-12-01 04:10
@glasser thanks for spotting that. I think that logic sounds incorrect, certainly. If someone wants to send a PR with a fix, that'd be super.
