### ISSUE TITLE
SSR: getDataFromTree works only for the first nested level of components in the tree

### ISSUE THREAD

**Issue by graphan** [apollostack/react-apollo#250] opened 2016-10-07 14:31 UTC
## Steps to Reproduce

I have the following structure of components (you can create own with such a structure):

```
├── App
   ├── Header
   |     |── Menu*
   |     |── Lang*
   |
   └── Page*
```

Components with asterixs are connected with graphql queries. Unfortunately, only data for Page component are fetched during Server Side Rendering.
It is depicted in [this project](https://github.com/WeLikeGraphQL/universal-react-apollo-example). Execute [these steps](https://github.com/WeLikeGraphQL/react-apollo-example#running-the-app) to run the project.
### Buggy Behavior

`getDataFromTree` does not work as expected in [this sample](https://github.com/WeLikeGraphQL/universal-react-apollo-example/blob/master/app/server.js#L46).
GraphQL query was executed only for Page Component. It can be checked in `window.__APOLLO_STATE__`. There is no execution for Menu and Lang Components.
### Expected Behavior

`getDataFromTree` should execute queries for all component tree structure, not only the first nested level of components.
### Version
- apollo-client@0.4.20
- react-apollo@0.5.7

**Comment by tmeasday** [comment] 2016-10-17 02:02
Hi @graphan -- it is possible to boil it down to a simpler reproduction?

Certainly I would expect `getDataFromTree` to work in your case. A quick inspection of your code makes it look like it should work.

I wasn't able to run your example above -- in which directory am I supposed to run `npm install`?

It would be easier to run an example against a simpler server;

a) ideally as a test, you could add one to this file: https://github.com/apollostack/react-apollo/blob/master/test/react-web/server/index.test.tsx

b) or against a know graphql server, for instance:
 i) you could use https://github.com/apollostack/frontpage-api OR
 ii) http://graphql-swapi.parseapp.com

**Comment by tmeasday** [comment] 2016-10-17 02:06
Interestingly I added a test to try and replicate (https://github.com/apollostack/react-apollo/pull/275/commits/65127351a7f90a316ed38c71f42569568021eeeb) and although it works normally, it fails when running w/ `NODE_ENV=production`.

Are you doing that?

**Comment by graphan** [comment] 2016-10-18 18:21
@tmeasday, thank you for the reaction.

Maybe, I misled you posting execution steps above (already deleted). Please, just execute [these steps](https://github.com/WeLikeGraphQL/react-apollo-example#running-the-app).

[This server](https://github.com/WeLikeGraphQL/wordpress-graphql-api-example) was set up in order to prove that `react-apollo` can be used against every GraphQL API (even the one created by [graphql-php](https://github.com/webonyx/graphql-php)). All is set up to be run almost automatically by vagrant, ansible, docker or.... manually... what you wish :)

Yes, I use `NODE_ENV=production`, but the interesting fact is that when I am not using it, the problem still occurs.

The other thing that might be important is that I use `graphql@0.4.14`, because it works seamlessly with `graphql-php`. Might the old version of `graphql` be the issue?

**Comment by graphan** [comment] 2016-10-18 18:43
@tmeasday, currently you need to set up sample data [manually](https://github.com/WeLikeGraphQL/wordpress-graphql-api-example#sample-data), so please wait until I do it all automatic. I will let you know.

**Comment by graphan** [comment] 2016-10-19 13:22
@tmeasday, [the server](https://github.com/WeLikeGraphQL/wordpress-graphql-api-example) has been already updated. You can launch it using one/two commands on every OS. I tried to do it as automatic as possible. You can try it.

Meanwhile, I will try to reproduce the issue against any simpler server.

**Comment by graphan** [comment] 2016-10-19 18:34
I have already applied your hints. I just forked `react-apollo-example` and made it compatible with: https://github.com/apollostack/frontpage-server.

Fork here: https://github.com/graphan/react-apollo-example
The only [changes](https://github.com/graphan/react-apollo-example/commit/be213f427e09fa9339d4542659e28688bd228a85) that I applied. Please, don't laugh at Readme :)

Unfortunately, the problem still occurs. You can open web console and check __APOLLO_STATE__.
Two things there:
 - query is only executed for Page Component
 - query is executed two times (I think that it is due to using Redux and updating state, but how to avoid it?)

**Comment by bkniffler** [comment] 2016-10-31 01:55
I got the same issue, works fine while developing, but in my production build there is only one level of data fetched.

**Comment by tmeasday** [comment] 2016-11-03 04:30
@bkniffler can you tell if you are getting the production version of React locally? You can tell easily by e.g. passing incorrect prop types; does it log a long warning?

**Comment by bkniffler** [comment] 2016-11-03 12:05
Yes, I just checked it and I'm certain to be running production version. Especially, since react throws a warning if minified and non production. Haven't you been able to reproduce the issue on your side?

**Comment by tmeasday** [comment] 2016-11-04 00:01
I guess I am wondering about the odd behaviour you are seeing when the issue doesn't happen locally. I've seen the bug in production mode in OSX.

**Comment by tmeasday** [comment] 2016-11-07 00:48
This is probably fixed on `refactor-ssr` if you are game to give it a try.

**Comment by bkniffler** [comment] 2016-11-07 10:56
Unfortunately it seems like the problem persists. If it helped, I could give you access to the private repository on bitbucket and heroku server, so you can take a look, experiment with your code on an affected repository and push to the server to see if you can find the cause within react-apollo (which I just pulled in as a webpack alias, so the react-apollo code is now part of the repository).

**Comment by bkniffler** [comment] 2016-11-07 15:28
I got multiple problems when using refactor-ssr branch. 

- walkTree throws undefined on `var Component = element.type;`, as element isn't defined
- same goes for `getQueriesFromTree -> walktree -> var Component = element.type || element;`
- if I fix these by making sure that element is defined, React-Router v4 throws an error in https://github.com/ReactTraining/react-router/blob/v4/modules/MatchProvider.js#L56 (context is undefined), which is called by `walkTree -> instance_1.componentWillMount();` 
- then https://github.com/ReactTraining/react-router/blob/v4/modules/createServerRenderContext.js#L25 causes issues (Cannot set property 'hasMissComponent' of undefined)
- Same for here https://github.com/ReactTraining/react-router/blob/v4/modules/createServerRenderContext.js#L42
- After manually fixing all those, `getDataFromTree(app).then((apolloContext) =>`, apolloContext is null (I suspect due to `return Promise.all(mappedQueries).then(function (_) { return null; });` in apollo-react/server -> getDataFromTree

Using the current react-apollo/server.js makes all these problems disappear again.

**Comment by bkniffler** [comment] 2016-11-07 15:53
I'm revisiting this bug (with react-apollo master branch), but I can't find anything that would explain this behaviour. I've inserted some console.logs into my code and its clear that on the server, render is only called once on the components, which results in only one level of data being resolved, while locally on my workmachine render is called multiple times (at least 4 times). Still talking about the exact same code running on both machines, dunno where the differences come from.

**Comment by tmeasday** [comment] 2016-11-08 01:07
Hi @bkniffler; thanks for investigating further.

It sounds like the new branch has a few rough edges, thanks for helping me sort them out.

A) How do you get `null` elements into `walkTree`?
B) How did you work around the context issue w/ RR? What was it being caused by?

If you are feeling keen, perhaps you could submit a PR to the `refactor-ssr` adding some simple tests to https://github.com/apollostack/react-apollo/blob/d127d02c0b938ca40d2da953ab133c45d310a402/test/react-web/server/index.test.tsx#L35 that exhibit the behavior? (and we can work to fix them). Otherwise a little more detail here and I'll try to get it going.

On the last point, `getDataFromTree` no longer returns the context (see the top comment in https://github.com/apollostack/react-apollo/pull/313). If you want the state, you can just call `client.store.getState().apollo` or the like. I'll document this better soon.

**Comment by tmeasday** [comment] 2016-11-08 01:08
@bkniffler the only thing I'm aware of is the issue mentioned here: https://github.com/apollostack/react-apollo/pull/259 where the old SSR code did something funky that threw an exception in development, and led to a different code path in the two cases.

But you said that you were running React in production locally so I can't really suggest anything else. Is it possible that on the server the queries are not returning the same thing? (Perhaps an error?)

**Comment by bkniffler** [comment] 2016-11-08 08:42
Yesterday I was totally focused on trying to fix the master branch after being frustrated with the refactor-ssr one, but nothing worked. After your messages I thought I'd give the new branch a try and.. it works perfectly now, on the server and locally with react-router, code-splitting and nested data to the lowest level! 

It was actually quite easy to fix the refactor-ssr branch. Here is a PR: https://github.com/apollostack/react-apollo/pull/317

On a sidenote: I'd find it better if `renderToStringWithData` would return the markup and the data, even though it works fine to pull the state manually from client. But the name `renderToStringWithData` sounds like it should return the data (like it was before).

**Comment by graphan** [comment] 2016-11-12 10:47
@tmeasday or @bkniffler , could you tell me how to try `refactor-ssr` in the easiest way?
I mean that I added something like this to my `package.json`:
```json
"react-apollo": "apollostack/react-apollo#refactor-ssr",
```
However, this way is not correct. I cannot import `react-apollo`:
```js
import { graphql } from 'react-apollo';
```
How to do it seamlessly?

**Comment by bkniffler** [comment] 2016-11-12 13:23
@graphan Just create a file 'apollo-server-fix.js' or similar inside your project and insert the apollo server code (https://github.com/apollostack/react-apollo/blob/master/src/server.ts) and import that script to call getDataFromTree/renderToStringWithData. For the sake of comfortability and if you don't use typescript, here is a compiled version of the server.ts file that you can copy&paste: https://github.com/olymp/olymp/blob/master/graphql/apollo-server-fix.js

Since the patch just concerns this one file and function (getDataFromTree/renderToStringWithData), it should be enough as a temporary fix until the branch gets merged and published.

**Comment by tmeasday** [comment] 2016-11-14 02:08
This is now out in 0.6.0. I think it fixes this issue.

**Closed by tmeasday** 2016-11-14 02:08 UTC
