### ISSUE TITLE
API idea for child components to communicate their GraphQL data requirements

### ISSUE THREAD

**Issue by saikat** [apollostack/react-apollo#110] opened 2016-07-14 15:05 UTC
Now that we have named fragment support (huzzah!) in Apollo, I was thinking a bit about how it would be cool if there was a simple API for child components to communicate their GraphQL data requirements to parent containers via fragments.  Relay's approach here is for every child component to, itself, be a container where the data requirements for each child are defined when creating the container.  The parent component is then responsible for injecting in the fragments required from the child component when creating its own container.  This works fine, but is a bit cumbersome and also means every child component has to be aware of Relay/makes the child components less reusable.

Thinking a bit more about it, I was wondering if we could actually just accomplish this using React's built in propTypes definitions.  What do you think of something like this (I think the API could probably be simplified further but it seems like there are some general API simplifications happening in this library so want to see what happens with that first): https://gist.github.com/saikat/338d6183019539520c3d044ffc8be085

This makes it so ChildComponent is actually reusable without necessarily needing its data from the backend and we keep our data-connected containers with implementation knowledge of how to actually get the data to a minimum.

**Comment by stubailo** [comment] 2016-07-14 16:42
@saikat I think there are a few things one might want to preserve when using fragments to split up queries:

1. Fragments and queries are statically analyzable, with tools like https://github.com/apollostack/eslint-plugin-graphql that can actually save you from writing invalid queries - this requires that they be strings and not arbitrary JSON objects
2. Fragments have meaningful names, so that you can identify them in your server-side tooling; this will help you indentify which parts of your server load are coming from where.
3. You should have access to all features of graphql, like inline conditional fragments, which aren't possible to reproduce in proptypes (GraphQL is a more powerful language than the proptypes DSL, IML)

IMO it's fine to have a component with a static fragment attached to it, and this doesn't make it any more coupled to the data fetching - the only issue with that is you have to duplicate the fragment and the proptypes. What if there was a simple way to generate the proptypes definition from the fragment?

This should be relatively simple to achieve with a script that looks at your schema and your fragment.

**Comment by saikat** [comment] 2016-07-14 21:55
Ah so generate proptypes from fragments instead of vice-versa.  That makes sense.  With createFragmentFromPropTypes, you would still get 3 (it would be, essentially, a helper to create fragments, but not the only way), and you could get 2 (the function could essentially create a fragment string with meaningful autogenerated fragment names), but 1 would probably be impossible.

**Comment by stubailo** [comment] 2016-07-19 00:59
Yeah, I just think it makes sense for it to be in that direction because you can't describe stuff like arguments using proptypes. I'd be happy to collaborate on something to auto-generate proptypes from fragments.

**Comment by jbaxleyiii** [comment] 2016-08-15 03:18
Closing in favor of common discussion in #140

**Closed by jbaxleyiii** 2016-08-15 03:18 UTC
Labels: enhancement, question
