### ISSUE TITLE
`returnPartialData: false` should set `loading: true`

### ISSUE THREAD

**Issue by cagdastulek** [apollostack/react-apollo#401] opened 2017-01-06 05:38 UTC
## Steps to Reproduce

1. Create a component A that queries like this:
```
query {
  foo {
  ...
  }
}
```
2. Have another component B that queries like this:
```
query {
  foo {
    ...
  }
  bar {
    ...
  }
}
```
3. Build an app that navigates from component A to component B to make sure that same store is used.

### Buggy Behavior

`data.loading` flag of the second component is `false` although networkStatus is 1. This bug happens even if component B uses `returnPartialData: false` option.

### Expected Behavior

`data.loading` flag should be `true` if returnPartialData is set to false.

### Version
- apollo-client@0.6.0
- react-apollo@0.8.1

### Remarks
- This can be because apollo client get confused as `foo` is already in the cache. However, according to current documentation, my understanding is that returnPartialData: false should prevent this.
- Related issue that was closed https://github.com/apollostack/apollo-client/issues/549 but I am not 100% sure why the developer decided to close it. Is he suggesting to not use `loading` indicator in such cases because it can not handle them?
- IMHO, `loading` indicator is one of the killer features of Apollo Client as it is one of the biggest pain points of using Redux/Flux which can only be solved with too much boilerplate code. In that regard, I highly recommend that this feature to be revisited.
- Current workaround of checking if `data.bar` exists or not is not ideal as it prevents someone using an Optional type for bar. In principle, this means that Apollo implementation prevents the proper usage of the GraphQL spec.

**Comment by cagdastulek** [comment] 2017-01-06 06:33
I was able to fix the "specific" issue with the following code change:
https://github.com/cagdastulek/apollo-client/commit/39103abf119b47d4927363b3163b947e2374407c

However, I am for sure far from being an authority to say if this is a good idea or not. Otherwise, I would be happy to turn it into a PR.

**Comment by stubailo** [comment] 2017-01-06 20:13
I think this is probably the best way to fix it: https://github.com/apollostack/apollo-client/issues/831

Like you said, networkStatus is correct, so we should just stop keeping track of `loading` separately. (We would still have that prop, it just wouldn't be tracked internally)

**Comment by stubailo** [comment] 2017-01-06 20:14
As a workaround, does checking `networkStatus` instead of `loading` work?

**Comment by stubailo** [comment] 2017-01-06 20:15
cc @helfer

**Comment by cagdastulek** [comment] 2017-01-06 23:43
`networkStatus` not ideal for my case because it will trigger again and again when I do a refetch, and if I use it for UI rendering, UI will flicker all the time.

The "cool" thing about the loading flag is that I can use it to show a "Loading" indicator to the user so that I can have my UI ready when the data is really there. And after that, I don't want that "Loading" indicator anymore. It is also good when loading = false but error is not null, so I can show the error to the user.

For the sake of brevity, I think Apollo client should make the following three states easy to distinguish:
1 - Data is not ready: loading = true error = null
2 - Data is ready but has errors: loading = false error = NetworkError | QueryError | etc
3 - Data is ready to use: loading = false error = false

Anything on top of that should be an optional/advanced feature.

**Comment by stubailo** [comment] 2017-01-07 00:09
Oh, I completely agree that loading should exist! I'm just wondering if network status works correctly. That's why I used the word "workaround". This is clearly a bug.

**Comment by calebmer** [comment] 2017-01-19 21:05
@cagdastulek Is this still broken with `0.7.x`? I just wrote a test trying to reproduce this error and it looks like everything is working fine.

**Comment by cagdastulek** [comment] 2017-01-25 01:37
@calebmer How do I upgrade react-apollo to apollo-client 0.7.x? It complains about missing dependency 0.6.0 when I do npm shrinkwrap.

**Comment by cagdastulek** [comment] 2017-01-25 02:22
I have upgraded to apollo-client 0.8.0 and the behavior has improved but as far as I understand, it is not fully fixed.

In apollo-client version 0.6, `loading` is always 'false' even if `returnPartialData` is set to `false`. In apollo-client 0.8, when `returnPartialData` is set to false, `loading` flag starts as `false` (which is the missing part of the fix) and then switches to `true` while the missing data is loaded from backend and switches back to `false` once data is loaded. Here is example console.log:
```
version 0.6
(1) {loading: false, listings: Array[0], networkStatus: 7}
(2) {loading: false, listings: Array[0], networkStatus: 1}
(3) {loading: false, listings: Array[0], networkStatus: 1}
(4) {loading: false, listings: Array[465], networkStatus: 7}
version 0.8
(1) {loading: false, listings: Array[0], networkStatus: 7}
(2) {loading: true, listings: Array[0], networkStatus: 1}
(3) {loading: true, listings: Array[0], networkStatus: 1}
(4) {loading: false, listings: Array[465], networkStatus: 7}
```

So, things improved but not ready.

By the way, it is a bummer that react-apollo is still expecting apollo-client version 0.6.0 while apollo-client now has 0.8.0. Why are these closely related projects not in sync?

**Comment by helfer** [comment] 2017-01-27 00:28
@cagdastulek Thanks! We've just released react-apollo 0.9, so if you want you can try that :)

We're removing partialData from the API soon, so I'm going to close this issue for now.

**Closed** 2017-01-27 00:28 UTC
Labels: wontfix

**Comment by cagdastulek** [comment] 2017-01-27 18:39
@helfer Thanks! I will check out. Is there any thread on Github or else that I can read to understand the reason(s) about why partialData will be removed?

**Comment by calebmer** [comment] 2017-01-28 00:26
@cagdastulek why do you want partial data?

If we return partial data we would be returning data that is inconsistent with the query the user wrote. This is undesirable for a number of reasons, one of the more important reasons is that a user could never depend on a non-null field actually being non-null.

I would be interested to know if you have a use case for partial data. We can’t think of one.

**Comment by cagdastulek** [comment] 2017-01-30 17:32
It should be ok for most cases like list -> edit where the extra information one wants to render in Edit stage can be a separate component querying the extra information.

One case, however, would be much easier with partial support, Admin/Owner checks:
- Say I have a flag like isOwner, which is expensive/makes no sense to calculate for each list item
- In detail view, I want to have the isOwner field but this will cause the page to wait for data
- And the problem is, 99% of traffic would not need isOwner field, so this causes the whole page to render slower for 100% of traffic for no reason.

What is the solution/best practice for such cases? To make the components that rely on isOwner field to have be wrapped by a separate gql query, too?

**Comment by calebmer** [comment] 2017-01-30 17:56
Well, in this case, we have special support for `@skip` and `@include` directives that allow for specific cases where you need partial data. As another note, you could always allow partial data yourself by using a nameless fragment like: `{ a b ... { c } }` where `c` would then be optional.

When I say I can’t think of a case for partial data it’s probably important to clarify (which I didn’t do initially…) that I’m only thinking about not allowing partial data when it is not explicit. So for instance:

```graphql
{
  a
  b
  c
}
```

Should *never* return an object without `c`. However queries like:

```graphql
{
  a
  b
  ... {
    c
  }
}
```

```graphql
{
  a
  b
  ... on Foo {
    c
  }
}
```

```graphql
{
  a
  b
  c @skip(if: true)
}
```

All have explicitly marked the `c` field as optional. In this case we want to respect the specification and allow `c` to be optional.

Does that make more sense?

**Comment by cagdastulek** [comment] 2017-01-30 18:00
Thanks for quick response. I didn't know much about `@skip` and `@include` directives. I guess I should read more about them. Intuitively, I liked that such stuff is moved to the language itself rather than implementations.
