### ISSUE TITLE
Proposal: Relay-like containers

### ISSUE THREAD

**Issue by rricard** [apollostack/react-apollo#122] opened 2016-07-28 15:39 UTC
Hello!

I know that being Relay is not a goal of Apollo but since the fragments appeared, I'm asking myself if we can do a similar system to what Relay is proposing with Routes and Containers.

Basically, I think that instead of only be able to associate a component to a query in a `connect` HOC, we should allow to associate named fragments exposed to the rest of the world.

We won't handle stuff like inferring variables up to the query using the schema introspection (what Relay does to add variables to the query using the `babel-relay-plugin`).

That would give us something like this:

```js

import React from 'react';
import {connect} from 'apollo-client';
import gql from 'graphql-tag';

const Person = props =>
  <li>
    <h1>{props.person.name}</h1>
    <img src={props.person.picUrl} />
  </li>;

const PersonWithData = connect({
  mapFragmentsToProps: () => ({
    person: {
      fragment: gql`
        fragment on Person {
          name
          picUrl(size: $picSize)
        }
      `,
      variables: {
        picSize: 200,
      },
    },
  }),
})(Person);

const People = props =>
  <ul>
    {props.people.people.map(person =>
      <PersonWithData person={person} key={person.id} />)
    )}
  </ul>;

const PeopleWithData = connect({
  mapQueriesToProps: () => ({
    people: {
      query: gql`
        # note that we can't infer that since we don't want to apply a
        # babel transform here...
        # However, the client could just strip the unused variables
        # before sending that to the server
        query(cursor: ID!, picSize: Int!, unused: String) { 
          people(cursor: $cursor) {
            id
            ...${PersonWithData.getFragmentName('person')}
          }
        }
      `,
      variables: {
        ...PersonWithData.getFragmentVariables('person'),
        cursor: null,
      }
    },
  }),
});
```

Just tell me what you think about it. I think it could help a lot with structuring codebases!

**Comment by stubailo** [comment] 2016-07-28 15:53
I think a couple of people have mentioned that the current fragment API isn't good for them - we should evaluate this and pick the best thing! One aspect I was hoping to stay away from is automatically generating queries or fragments at all so that the queries you type in your code can be maximally similar to what you log on your server. Once you start doing random fragment names stuff that arrives on the server starts looking very different. Is this a concern for anyone? Perhaps it's not an important issue.

Also, I'm curious about use cases for fragments that could instead be solved with the batching feature. Batching makes it much more okay to have many root queries instead of needing to do everything via fragments, but I'm interested to learn where the different approaches are preferable.

I don't think we should reproduce all of the features of Relay one by one, but rather is there a simpler way to get some of the same benefits?

**Comment by rricard** [comment] 2016-07-28 15:59
I agree The core idea behind this proposal (that may have not been clear) is to get the benefits behind the relay containers without needing a babel plugin.

**Comment by rricard** [comment] 2016-07-28 16:10
And definitely, this should only be a `react-apollo` thing. This has nothing to do at client-level.

**Comment by stubailo** [comment] 2016-07-28 16:11
Btw, here's one good reason not to randomize fragment names: https://github.com/graphql/express-graphql/pull/109

One thing that would help me more is specificity:

> the benefits behind the relay containers

Which benefits are we talking about? Relay containers do a lot of stuff, so it's hard to know exactly which things we are thinking about here.

**Comment by rricard** [comment] 2016-07-28 16:15
Yep, mainly, it is just colocating the fragment with the component (I know there are ways to do that without containers) but I'm mainly interested in colocating the variables linked to the what's in the fragments as well. Randomizing is not required, actually, I agree it's not that great and since we have a parsed AST with`gql`, we could just extract the name of the fragment.

**Comment by rricard** [comment] 2016-07-28 16:18
In fact, given the example, let's say I'm in `Person` and I want to refetch with new vars, today, I still need to pass the complete `people` query result to be able to refetch. With this proposal, I could just refetch on the fragment (ultimately retriggering the query) but it doesn't need me to pass along the root of the query all the way down my component tree...

**Comment by rricard** [comment] 2016-07-28 16:19
(and of course, we can extend that to `fetchMore` :wink:)

**Comment by rricard** [comment] 2016-07-28 16:21
Again, the current fragment implementation is really good for what I do. I'm just asking for more sugar! (and I would be ready to implement that sugar)

**Comment by stubailo** [comment] 2016-07-28 16:21
So the main issue with that seems to be that if you change the fragment variables from the inner component, you are setting a global variable on the whole GraphQL query, which means any other component using that fragment will also get the data with the new variables?

(BTW I'm not against this general idea, I just want to get down to really specific details so that we can work out any potential problems ahead of time)

**Comment by rricard** [comment] 2016-07-28 16:25
No, it's not even that, if that was the issue, that would need I have an issue on how my schema work. I don't mind having the rest updated. I mind having to pass down the root of the query in react down to the smallest components (that shouldn't care about the whole query results). Let's take the example again, one Person shouldn't have all of the People data just in order to perform a refetch

**Comment by stubailo** [comment] 2016-07-28 16:27
For that specific concern, you could just pass down just the `refetch` callback. (Again, not against the proposal in general, just making sure we are talking in terms of concrete details)

**Comment by rricard** [comment] 2016-07-28 16:29
Yup that would be it (and kinda what I'm doing btw). But again, that would add some welcome sugar and force users to have a more structured codebase (for example force my colleagues to do this instead of doing whatever they want with fragments).

**Comment by rricard** [comment] 2016-07-28 16:30
It's not about the feature, it's more about structuring (the feature is there). but I agree, it's not a vital need!

**Comment by stubailo** [comment] 2016-07-28 16:31
So I guess the idea is that a fragment, rather than being a static object that is included in a query, can be a "smart" object with some special methods like refetching, setting variables, reading from the store directly, etc? I think that does make sense, even if it is only for code structure purposes.

**Comment by rricard** [comment] 2016-07-28 16:31
Exactly!

**Comment by stubailo** [comment] 2016-07-28 16:39
I think it makes sense to have this as a core feature! That way it can be shared between view integrations, and all react Apollo has to do is attach that standard object to the component. Or is there some reason it should be a react specific thing?

**Comment by rricard** [comment] 2016-07-28 16:43
I thought of the example in a react setup and I have to admit I don't know the other implementations.

**Comment by rricard** [comment] 2016-07-29 00:53
@stubailo I'll try to translate this proposal to core and try to implement it then in my free time.

**Comment by jbaxleyiii** [comment] 2016-08-15 03:18
Closing in favor of common discussion in #140

**Closed by jbaxleyiii** 2016-08-15 03:18 UTC
Labels: enhancement, question
