### ISSUE TITLE
Query strange behavior - unlimited loading state after success mutation

### ISSUE THREAD

**Issue by ARMGAMES** [apollostack/react-apollo#368] opened 2016-12-09 21:30 UTC
I have a simple react component that connect to graphql query and all works fine untill i add new element to my db with mutation. 

**my simple react component - SpeakerList**
```
import React from 'react';
import { graphql } from 'react-apollo';

import { QuerySpeakerList } from '../../../redux/graphql/querys';

import SpeakerListItem from './SpeakerListItem';

class SpeakerList extends React.Component {
    render( ) {
        const { loading } = this.props.data;

        console.log('SpeakerList', this.props.data);

        if (loading)
            return (
                <h1>Loading</h1>
            )

        return (
            <h1>do stuff</h1>
        )
    }
}

SpeakerList.propTypes = {
    data: React.PropTypes.object.isRequired
};

export default graphql(QuerySpeakerList)(SpeakerList);
```

I add new element with modal window that i make with component that i connect with that.
```
const Query = graphql(QuerySpeakerList, { name: 'Speakers' });
const Mutation = graphql(MutationAddSpeaker, {
    name: 'addSpeaker',
    options: {
        updateQueries: {
            Speakers: (prev, { mutationResult, queryVariables }) => {
                return {
                    speakers: [
                        ...prev.speakers,
                        mutationResult.data.addSpeaker
                    ]
                }
            }
        }
    }
});

export default compose( Query, Mutation )( AddSpeaker );
```
Mutation works fine even updateQueries runs and adding new element to array, but when i close modal window i has my Query element at unlimited loading state. I show that at screenshot.
![2016-12-10_00-08-38](https://cloud.githubusercontent.com/assets/20094067/21064994/262ccedc-be6f-11e6-9922-6c6870dffea4.png)

**QuerySpeakerList**
```
export const QuerySpeakerList = gql `
    query Speakers{
        speakers {
            ...speakerInfo
        }
    }
    ${SpeakerFragment}
`;
```
**SpeakerFragment**
```
export const SpeakerFragment = gql `
    fragment speakerInfo on Speaker {
        id
        url
        body
        name
        avatar
        description
        likes {
            id
        }
        comments{
            id
        }
        courses {
            id
        }
    }
`;
```

**MutationAddSpeaker**
```
export const MutationAddSpeaker = gql `
    mutation addSpeaker($name: String!, $url: String!, $avatar: String!, $description: String!, $body: String!){
        addSpeaker(name: $name, url: $url, avatar: $avatar, description: $description, body: $body){
            id
            url
            name
            avatar
            description
            body
        }
    }
`;
```

What i do wrong?

### Version
- apollo-client@0.5.12
- react-apollo@0.6.0

**Comment by ARMGAMES** [comment] 2016-12-09 22:23
I think i have same issue with #361

**Comment by ARMGAMES** [comment] 2016-12-13 01:57
Any ideas?

**Comment by helfer** [comment] 2016-12-13 17:05
@ARMGAMES this looks like it could be a bug in apollo-client. Would you mind opening the issue there and make sure it occurs with the latest version of apollo-client? (it probably does)

**Comment by jbuchermn** [comment] 2016-12-13 19:50
I'm currently battling, I think, the same issue.

Could you try querying the whole SpeakerFragment in your mutation? Like

`mutation addSpeaker($name: String!, $url: String!, $avatar: String!, $description: String!, $body: String!)    {
        addSpeaker(name: $name, url: $url, avatar: $avatar, description: $description, body: $body){
            ...speakerInfo
        }
    }
    ${SpeakerFragment}`

This worked for me, at least apollo-client didn't crash anymore. I don't consider this a fix though, since querying partial information here should be possible.

**Comment by ARMGAMES** [comment] 2016-12-14 05:34
Created issue at apollo - https://github.com/apollostack/apollo-client/issues/1039

**Comment by SachaG** [comment] 2016-12-15 01:58
I'm also encountering weird behaviors around the `loading` state. It often gets stuck to `true` or `false` when it shouldn't.

**Comment by SachaG** [comment] 2016-12-15 02:42
@jbuchermn I can confirm that the problem comes from using partial fragments and is fixed by using  the entire fragment. To clarify, I'm using a reducer to optimistically insert the results from a new mutation. 

When the new mutation returns a partial fragment (compared to the other documents in the list which were previously loaded from the server), the reducer's return value is never passed to the returned `props` and `data.loading` is set to `true` indefinitely. 

When the new mutation returns a full fragment, everything works properly.

**Comment by helfer** [comment] 2016-12-16 01:36
Closing this issue now that we're tracking it in https://github.com/apollostack/apollo-client/issues/1039

**Closed by helfer** 2016-12-16 01:36 UTC
