### ISSUE TITLE
Upgraded to 0.3.3 getting error in diffFieldAgainstStore

### ISSUE THREAD

**Issue by mattiasewers** [apollostack/react-apollo#47] opened 2016-05-10 09:20 UTC
Just upgraded to the latest version and getting `Error: Can't find field user on object [object Object].`in diffFieldAgainstStore, worked great with 0.2.1.

**Comment by mattiasewers** [comment] 2016-05-10 09:58
Tested to downgrade `0.3.1` and it works, latest does not

**Comment by jbaxleyiii** [comment] 2016-05-10 12:47
@mattiasewers can you provide a code sample of your query? And what version of `apollo-client` are you using?

**Comment by mattiasewers** [comment] 2016-05-10 12:59
@jbaxleyiii Thanks for answering! Using `apollo-client@0.3.4`.  Here's an example query: `
        query {
          user {
            projects{
              title
            }
          }
        }
`, I've also tested my queries against graphiql, which works as expected.

**Comment by NeoPhi** [comment] 2016-05-10 17:47
Sounds similar to the issue I'm seeing in #46 which appeared after I upgraded from `0.3.1` to `0.3.3`.

**Comment by jbaxleyiii** [comment] 2016-05-10 18:11
@NeoPhi @mattiasewers I can confirm this bug! I'm not sure if the issue is in the `apollo-client` or `react-apollo` but I'm tracking it down. For now, if you turn `partialData` and `forceFetch` to false, do you still get the issue?

**Comment by stubailo** [comment] 2016-05-10 18:13
Sounds like it's in `apollo-client` to me! I messed with diffing quite a bit last week, and could have messed this up in the process.

**Comment by stubailo** [comment] 2016-05-10 18:14
Closing in favor of: https://github.com/apollostack/react-apollo/issues/46

**Closed by stubailo** 2016-05-10 18:14 UTC

**Comment by stubailo** [comment] 2016-05-11 03:37
This should be fixed in Apollo Client 0.3.5. Please let me know if it isn't!

**Comment by mattiasewers** [comment] 2016-05-11 21:12
@stubailo Yes it's fixed
