### ISSUE TITLE
refetchQueries don't update components | bug

### ISSUE THREAD

**Issue by seeden** [apollostack/react-apollo#269] opened 2016-10-12 13:15 UTC
## Steps to Reproduce

I have component with

```js
@graphql(gql`
  query getViewer {
    viewer {
      id,
    }
  }
`, {
  props: ({ data: { loading, viewer, error } }) => ({ loading, viewer, error }),
})
export default class ViewerProvider extends Component {
  render() {
    const { children, loading, viewer, error } = this.props;
    console.log(loading, viewer, error);
    return children;
  }
}
```

1. When user is not logged in - viewer is not defined. (I can see in the console that viewer is not defined)
2. After login I am calling refetchQueries: ['getViewer']
3. Query to server looks like this

```
query ___composed {
  ___getViewer___requestIndex_0___fieldIndex_0: viewer {
    id
    __typename
  }
}
```

and response looks like this:

```js
{"data":{"___getViewer___requestIndex_0___fieldIndex_0":{"id":"1","__typename":"User"}}}
```

But my component is not updated. There is no info in the console. 

### Expected Behavior

Component will be updated properly with new data from server

### Version
- apollo-client@0.4.20
- react-apollo@0.5.7 and 0.5.9 too

**Comment by seeden** [comment] 2016-10-12 13:26
I have tried to turn off batching. But this issue is still here.

Query looks like this
```js
{
operationName: "getViewer"
query: "query getViewer {↵  viewer {↵    id↵    __typename↵  }↵}↵"
variables: {}
}
```

and response is correct too but component has old data

**Comment by seeden** [comment] 2016-10-12 14:33
Here is more info about this issue.
There is a problem only with components which are already mounted. If I am using new component this component will get correct data.

**Comment by seeden** [comment] 2016-10-12 15:14
After debugging react-apollo I found that component is subscribed but there is no next call.
That means the problem is somewhere in the apollo-client.

**Comment by stubailo** [comment] 2016-10-12 17:24
Looks like the problem is indeed in apollo client. Going to close this issue and try to fix there.

**Closed by stubailo** 2016-10-12 17:24 UTC

**Comment by seeden** [comment] 2016-10-13 15:04
Maybe it is a problem with react-apollo because component will stay in state **loading === true** forever.

**Comment by seeden** [comment] 2016-10-13 15:52
The problematic line in react-apollo is https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L382

As you can see loading will be changed to value "true". But this function is called from componentWillReceiveProps and no componentDidMount. Anyway after that loading value will be equals true forever.

**Comment by akomm** [comment] 2017-06-22 09:18
Links to branches are not useful because branches move. pointing to a commit or tag is always better.
I have the same issue and I do not understand why unresolved issues is closed. Any updates on this?

**Comment by marlonmleite** [comment] 2017-06-30 20:21
@seeden @stubailo i have same problema, any solution?

**Comment by marlonmleite** [comment] 2017-06-30 21:42
It's ok, if use:
`refetchQueries: [{ query: MyQuery }]`

It's not update property loading and not update view:
`refetchQueries: ['MyQuery']`

**Comment by liz-mars** [comment] 2017-07-20 22:01
I appear to be having this problem as well. Any known workarounds?

**Comment by akomm** [comment] 2017-07-21 09:56
@marlonmleite where do you have the second variant from? I only know the first one from docs, so it would not surprise why the second variant you'v posted does not work.

**Comment by jonathanphz** [comment] 2017-08-16 16:49
I'm having the same issues I think - refetchQueries only works sometimes not sure why. Been having a terrible time trying to make this work for a few days now.

so: "Looks like the problem is indeed in apollo client. Going to close this issue and try to fix there."

is there a link to the issue **there**?

**Comment by rodcisal** [comment] 2017-08-18 13:38
Having the same problem
It's so weird cause sometimes it works perfectly but most of the times it doesn't
Is there any alternative to refetchQueries?

**Comment by seeden** [comment] 2017-08-18 13:40
do you have everywhere id   in your queries ( I mean in all sub fields)?
apollo-client have a lot of problems if field id is missing

**Comment by iamrommel** [comment] 2017-10-21 12:52
@marlonmleite 

> 
> It's not update property loading and not update view:
> refetchQueries: ['MyQuery']

i have been using this varient of refetchQueries for sometime but now it does not work!

**Comment by iamrommel** [comment] 2017-10-21 12:57
@akomm ,http://dev.apollodata.com/react/api-mutations.html#graphql-mutation-options-refetchQueries here is the documentation for that second variant of refetchQueies
